apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-sqlite-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi-sqlite-app
  template:
    metadata:
      labels:
        app: fastapi-sqlite-app
    spec:
      containers:
        - name: fastapi-container
          image: prakhardockerhub/fastapi-sqlite-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_PASSWORD
