apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-sqlite-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi-sqlite-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fastapi-sqlite-app
    spec:
      containers:
        - name: fastapi-container
          image: prakhardockerhub/fastapi-sqlite-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://myuser:mypassword@postgres-service:5432/mydb"
